name: projekt_hive
description: Eine iOS App zur Verwaltung von Projekten, Artikeln und Bildern
publish_to: 'none'
version: 1.0.1+1

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  cupertino_icons: ^1.0.6
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_bloc: ^9.1.1
  project_hive_backend:
    path: project_hive_backend
  provider: ^6.1.1
  path_provider: ^2.1.2
  uuid: ^4.2.1
  intl: ^0.19.0
  image_picker: ^1.0.7
  pdf: ^3.10.7
  printing: ^5.11.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  modal_bottom_sheet: ^3.0.0-pre
  google_fonts: ^6.1.0
  equatable: ^2.0.7
  stream_transform: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.8
  hive_generator: ^2.0.1

flutter:
  uses-material-design: false

  generate: true
